// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var assert, imgLoaded, isNumber;
  assert = require('assertive');
  imgLoaded = require('./imgLoaded_client');
  isNumber = require('underscore').isNumber;
  module.exports = function (driver) {
    return {
      imgLoaded: function (selector) {
        var cache$, doc, fail, help, result;
        if (arguments.length > 1) {
          cache$ = arguments;
          doc = cache$[0];
          selector = cache$[1];
          cache$;
        }
        assert.hasType('imgLoaded(selector) - requires (String) selector', String, selector);
        fail = function (message) {
          if (null != doc)
            message = '' + doc + '\n' + message;
          throw new Error(message);
        };
        selector = JSON.stringify(selector);
        result = driver.evaluate('return (' + imgLoaded + ')(' + selector + ');');
        if (result === true)
          return;
        if (result === 0) {
          help = 'element not found';
        } else if (isNumber(result)) {
          help = 'non-unique selector; count: ' + result;
        } else {
          help = 'failed to load ' + result;
        }
        return fail('imgLoaded ' + selector + ': ' + help);
      }
    };
  };
}.call(this);
