// Generated by CoffeeScript 2.0.0-beta7
module.exports = function (selector) {
  var describe, img, imgs, oops;
  describe = function (elem) {
    var classes, tag;
    tag = null != elem.tagName ? elem.tagName.toLowerCase() : void 0;
    if (null != tag)
      tag;
    else
      tag = '';
    if (elem.id)
      tag += '#' + elem.id;
    if (classes = elem.className.replace(/^\s+|\s+$/g, ''))
      tag += '.' + classes.replace(/\s+/g, '.');
    return tag;
  };
  img = (imgs = document.querySelectorAll(selector))[0];
  if (!(imgs.length === 1))
    return imgs.length;
  if (!img.src) {
    oops = describe(img);
    if (null != img.tagName ? img.tagName.match(/^img$/i) : void 0) {
      oops = 'src-less ' + oops;
    } else {
      oops = 'non-image ' + oops;
    }
    return oops;
  }
  if (img.complete && img.naturalWidth) {
    return true;
  } else {
    return img.src;
  }
};
