// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var buildElementAsserts, buildImgLoadedAsserts, buildNavigationAsserts, extend, imgDiff;
  extend = require('underscore').extend;
  buildElementAsserts = require('./element');
  buildNavigationAsserts = require('./navigation');
  buildImgLoadedAsserts = require('./imgLoaded');
  imgDiff = require('../img_diff');
  module.exports = function (testium) {
    var asserts;
    asserts = {};
    extend(asserts, buildElementAsserts(testium.driver));
    extend(asserts, buildNavigationAsserts(testium));
    extend(asserts, buildImgLoadedAsserts(testium.driver));
    extend(asserts, imgDiff);
    return asserts;
  };
}.call(this);
