// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var assert;
  assert = require('assertive');
  module.exports = function (api) {
    return {
      httpStatus: function (expectedStatus) {
        var actualStatus;
        assert.hasType('assert.httpStatus(status) - requires (Number) status', Number, expectedStatus);
        actualStatus = api.getStatusCode();
        return assert.equal('statuscode', expectedStatus, actualStatus);
      }
    };
  };
}.call(this);
