// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var BIN_PATH, browserName, optimist, options, USAGE;
  USAGE = 'Usage: $0 [browser | --update-selenium | --force-update | --help]';
  BIN_PATH = '' + __dirname + '/../../bin';
  optimist = require('optimist').usage(USAGE);
  options = optimist.argv;
  if (options['update-selenium']) {
    require('selenium-download').update(BIN_PATH, function () {
      return process.exit(0);
    });
  } else if (options['force-update']) {
    require('selenium-download').forceUpdate(BIN_PATH, function () {
      return process.exit(0);
    });
  } else if (options.help) {
    console.log(optimist.help());
  } else {
    browserName = options._[0] || 'firefox';
    require('./console')(browserName);
  }
}.call(this);
