// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var binPath, browserName, optimist, options, USAGE;
  USAGE = 'Usage: $0 [browser|--updateSelenium|--help]';
  optimist = require('optimist').usage(USAGE);
  options = optimist.argv;
  if (options['update-selenium']) {
    binPath = '' + __dirname + '/../../bin';
    require('selenium-download').update(binPath, function () {
      return process.exit(0);
    });
  } else if (options.help) {
    console.log(optimist.help());
  } else {
    browserName = options._[0] || 'firefox';
    require('./console')(browserName);
  }
}.call(this);
