// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var hasType;
  hasType = require('assertive').hasType;
  module.exports = function (driver) {
    return {
      accept: function () {
        return driver.acceptAlert();
      },
      dismiss: function () {
        return driver.dismissAlert();
      },
      getText: function () {
        return driver.getAlertText();
      },
      type: function (text) {
        hasType('type(text) - requires (String) text', String, text);
        return driver.typeAlert(text);
      }
    };
  };
}.call(this);
