// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var extend, inferConsoleLogs, semver;
  semver = require('semver');
  extend = require('underscore').extend;
  inferConsoleLogs = function (capabilities) {
    var lt197, phantomjs;
    phantomjs = capabilities.browserName === 'phantomjs';
    if (phantomjs) {
      lt197 = semver.satisfies(capabilities.version, '<1.9.7');
      if (lt197)
        return 'none';
      return 'basic';
    }
    return 'all';
  };
  module.exports = function (capabilities) {
    var testium;
    testium = {};
    testium.consoleLogs = inferConsoleLogs(capabilities);
    extend(capabilities, { testium: testium });
    return capabilities;
  };
}.call(this);
