// Generated by CoffeeScript 2.0.0-beta7
module.exports = function (deprecatedMethod, successorMethod) {
  var message;
  message = '[testium] Warning: ' + deprecatedMethod + ' is deprecated and will be removed in a future major version.';
  if (null != successorMethod)
    message += ' Please use ' + successorMethod + ' instead.';
  message += '\n';
  return process.stdout.write(message);
};
