// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, deprecate, elementExistsFailure, elementExistsPredicate, getElementWithoutError, hasType, isntVisibleFailure, isntVisiblePredicate, isVisibleFailure, isVisiblePredicate, partial, truthy, visibleFailure, visiblePredicate, waitForElement;
  cache$ = require('assertive');
  truthy = cache$.truthy;
  hasType = cache$.hasType;
  getElementWithoutError = require('./safeElement');
  deprecate = require('./deprecate');
  partial = require('underscore').partial;
  waitForElement = function (driver, selector, predicate, failure, timeout) {
    var element, foundElement, start;
    if (null == timeout)
      timeout = 3e3;
    start = Date.now();
    driver.setElementTimeout(timeout);
    foundElement = null;
    while (Date.now() - start < timeout) {
      element = getElementWithoutError(driver, selector);
      if (predicate(element)) {
        foundElement = element;
        break;
      }
    }
    driver.setElementTimeout(0);
    if (foundElement === null)
      failure(selector, timeout);
    return foundElement;
  };
  visiblePredicate = function (shouldBeVisible, element) {
    return (null != element ? element.isVisible() : void 0) === shouldBeVisible;
  };
  visibleFailure = function (shouldBeVisible, selector, timeout) {
    var negate;
    negate = shouldBeVisible ? '' : 'not ';
    throw new Error('Timeout (' + timeout + 'ms) waiting for element (' + selector + ') to ' + negate + 'be visible.');
  };
  elementExistsPredicate = function (element) {
    return null != element;
  };
  elementExistsFailure = function (selector, timeout) {
    throw new Error('Timeout (' + timeout + 'ms) waiting for element (' + selector + ') to exist in page.');
  };
  isVisiblePredicate = partial(visiblePredicate, true);
  isntVisiblePredicate = partial(visiblePredicate, false);
  isVisibleFailure = partial(visibleFailure, true);
  isntVisibleFailure = partial(visibleFailure, false);
  module.exports = function (driver) {
    return {
      getElement: function (selector) {
        hasType('getElement(selector) - requires (String) selector', String, selector);
        return getElementWithoutError(driver, selector);
      },
      getElements: function (selector) {
        hasType('getElements(selector) - requires (String) selector', String, selector);
        return driver.getElements(selector);
      },
      waitForElement: function (selector, timeout) {
        deprecate('waitForElement', 'waitForElementVisible');
        hasType('getElements(selector) - requires (String) selector', String, selector);
        return waitForElement(driver, selector, isVisiblePredicate, isVisibleFailure, timeout);
      },
      waitForElementVisible: function (selector, timeout) {
        hasType('getElements(selector) - requires (String) selector', String, selector);
        return waitForElement(driver, selector, isVisiblePredicate, isVisibleFailure, timeout);
      },
      waitForElementNotVisible: function (selector, timeout) {
        hasType('getElements(selector) - requires (String) selector', String, selector);
        return waitForElement(driver, selector, isntVisiblePredicate, isntVisibleFailure, timeout);
      },
      waitForElementExist: function (selector, timeout) {
        hasType('getElements(selector) - requires (String) selector', String, selector);
        return waitForElement(driver, selector, elementExistsPredicate, elementExistsFailure, timeout);
      },
      click: function (selector) {
        var element;
        hasType('click(selector) - requires (String) selector', String, selector);
        element = driver.getElement(selector);
        truthy('Element not found at selector: ' + selector, element);
        return element.click();
      }
    };
  };
}.call(this);
