// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var errorMessage, imgDiff;
  imgDiff = null;
  errorMessage = '\nimg-diff failed to install on your system and cannot be used.\nmake sure you have libpng installed.\nUbuntu: sudo apt-get install libpng-dev\nOS X:   brew install libpng';
  try {
    imgDiff = require('img-diff');
  } catch (e$) {
    imgDiff = {
      imagesMatch: function () {
        throw new Error(errorMessage);
      },
      crop: function () {
        throw new Error(errorMessage);
      }
    };
  }
  module.exports = imgDiff;
}.call(this);
