// Generated by CoffeeScript 2.0.0-beta7
module.exports.tryParse = function (jsonString) {
  var error;
  try {
    return JSON.parse(jsonString);
  } catch (e$) {
    error = e$;
    error.message = 'Unable to parse JSON: ' + error.message + '\nAttempted to parse: ' + jsonString;
    throw error;
  }
};
