// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, hasType, isObject, omit;
  cache$ = require('underscore');
  isObject = cache$.isObject;
  omit = cache$.omit;
  hasType = require('assertive').hasType;
  module.exports = function (driver) {
    return {
      mouseOver: function (selector) {
        var element;
        hasType('mouseOver(selector) - requires (String) selector', String, selector);
        element = driver.getElement(selector);
        return driver.moveTo(element.elementId);
      }
    };
  };
}.call(this);
