// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var CHROME_MESSAGE, FIREFOX_MESSAGE, PHANTOMJS_MESSAGE;
  FIREFOX_MESSAGE = /Unable to locate element/;
  PHANTOMJS_MESSAGE = /Unable to find element/;
  CHROME_MESSAGE = /no such element/;
  module.exports = function (driver, selector) {
    var exception, message;
    try {
      return driver.getElement(selector);
    } catch (e$) {
      exception = e$;
      message = exception.toString();
      if (FIREFOX_MESSAGE.test(message))
        return null;
      if (PHANTOMJS_MESSAGE.test(message))
        return null;
      if (CHROME_MESSAGE.test(message))
        return null;
      throw exception;
    }
  };
}.call(this);
