// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, hasType, truthy;
  cache$ = require('assertive');
  truthy = cache$.truthy;
  hasType = cache$.hasType;
  module.exports = function () {
    return {
      sleep: function (timeout) {
        var start;
        hasType('sleep(timout) - requires (Number) timeout', Number, timeout);
        start = Date.now();
        return function (accum$) {
          while (Date.now() - start < timeout) {
            accum$.push(void 0);
          }
          return accum$;
        }.call(this, []);
      }
    };
  };
}.call(this);
