// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, isRegExp, isString;
  cache$ = require('underscore');
  isString = cache$.isString;
  isRegExp = cache$.isRegExp;
  module.exports = function (stringOrRegex, waitingFor, getValue, timeout) {
    var currentValue, lowerWaitingFor, start, success, test;
    test = null;
    if (isString(stringOrRegex)) {
      test = function (testUrl) {
        return stringOrRegex === testUrl;
      };
    } else if (isRegExp(stringOrRegex)) {
      test = function (testUrl) {
        return stringOrRegex.test(testUrl);
      };
    } else {
      throw new Error('waitFor' + waitingFor + '(urlStringOrRegex) - requires a string or regex param for the ' + waitingFor);
    }
    success = false;
    currentValue = null;
    start = Date.now();
    while (Date.now() - start < timeout) {
      currentValue = getValue();
      if (test(currentValue)) {
        success = true;
        break;
      }
    }
    if (!success) {
      lowerWaitingFor = waitingFor.toLowerCase();
      throw new Error('Timed out (' + timeout + 'ms) waiting for ' + lowerWaitingFor + ' (' + stringOrRegex + '). Last ' + lowerWaitingFor + ' was: ' + currentValue);
    }
  };
}.call(this);
