// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var assert;
  assert = require('assertive');
  module.exports = function (driver) {
    return {
      switchToDefaultFrame: function () {
        return driver.switchToDefaultFrame();
      },
      switchToFrame: function (indexOrNameOrId) {
        assert.truthy('switchToFrame(indexOrNameOrId) - requires (Number|String) indexOrNameOrId', indexOrNameOrId);
        return driver.switchToFrame(indexOrNameOrId);
      },
      switchToDefaultWindow: function () {
        assert.truthy('Attempted to locate the root window, but failed. Did you navigate to a URL first?', driver.rootWindow);
        return driver.switchToWindow(driver.rootWindow);
      },
      switchToWindow: function (name) {
        assert.truthy('switchToWindow(name) - requires (String) name', name);
        return driver.switchToWindow(name);
      },
      closeWindow: function () {
        return driver.closeWindow();
      }
    };
  };
}.call(this);
