/*
Copyright (c) 2013, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var AdmZip, async, BIN_PATH, cache$, CHROMEDRIVER_PATH, CHROMEDRIVER_TEMP_PATH, CHROMEDRIVER_VERSION, CHROMEDRIVER_ZIP_TEMP_PATH, copy, doneEvent, downloadFile, ensureChromeDriver, ensureSelenium, exists, exit, fs, getArchitecture, getLatestVersions, http, makePaths, mkdirp, move, SELENIUM_JAR_PATH, SELENIUM_TEMP_PATH, SELENIUM_VERSION, TEMP_PATH, unzip;
  fs = require('fs');
  http = require('http');
  mkdirp = require('mkdirp');
  async = require('async');
  AdmZip = require('adm-zip');
  cache$ = require('fs.extra');
  copy = cache$.copy;
  move = cache$.move;
  getLatestVersions = require('./versions');
  BIN_PATH = '' + __dirname + '/../../bin';
  TEMP_PATH = '/tmp/testium';
  CHROMEDRIVER_PATH = '' + BIN_PATH + '/chromedriver';
  CHROMEDRIVER_TEMP_PATH = '' + TEMP_PATH + '/chromedriver';
  CHROMEDRIVER_ZIP_TEMP_PATH = '' + CHROMEDRIVER_TEMP_PATH + '.zip';
  SELENIUM_JAR_PATH = '' + BIN_PATH + '/selenium.jar';
  SELENIUM_TEMP_PATH = '' + TEMP_PATH + '/selenium.jar';
  CHROMEDRIVER_VERSION = '2.8';
  SELENIUM_VERSION = '2.38.0';
  doneEvent = function () {
    var nodeVersion;
    nodeVersion = Number(process.version.match(/^v(\d+\.\d+)/)[1]);
    if (nodeVersion < .99) {
      return 'end';
    } else {
      return 'finish';
    }
  }();
  exists = function (filePath) {
    return fs.existsSync(filePath);
  };
  downloadFile = function (url, filePath, callback) {
    var file;
    file = fs.createWriteStream(filePath);
    return http.get(url, function (response) {
      response.pipe(file);
      return response.on(doneEvent, function () {
        return callback();
      });
    });
  };
  ensureSelenium = function (version) {
    return function (callback) {
      var binFilePath, file, tempFilePath, url;
      url = 'http://selenium.googlecode.com/files/selenium-server-standalone-' + version + '.jar';
      file = 'selenium.jar';
      binFilePath = '' + BIN_PATH + '/' + file;
      if (exists(binFilePath))
        return callback();
      console.log('[testium] grabbing selenium standalone server ' + version);
      tempFilePath = '' + TEMP_PATH + '/selenium_' + version + '.jar';
      if (exists(tempFilePath)) {
        return copy(tempFilePath, binFilePath, callback);
      } else {
        return downloadFile(url, tempFilePath, function () {
          return copy(tempFilePath, binFilePath, callback);
        });
      }
    };
  };
  getArchitecture = function () {
    var bitness, platform;
    platform = process.platform;
    if (!(platform === 'linux' || platform === 'darwin' || platform === 'win32'))
      throw new Error('Unsupported platform ' + platform + '. Only linux, darwin, and win32 are supported.');
    bitness = process.arch.substr(1);
    if (platform === 'darwin') {
      platform = 'mac';
      bitness = '32';
    }
    if (platform === 'win32') {
      platform = 'win';
      bitness = '32';
    }
    return {
      platform: platform,
      bitness: bitness
    };
  };
  unzip = function (filePath, callback) {
    var tempFilePath;
    tempFilePath = '' + filePath + '.tmp';
    return move(filePath, tempFilePath, function () {
      var zip;
      zip = new AdmZip(tempFilePath);
      zip.extractAllTo(TEMP_PATH);
      fs.unlinkSync(tempFilePath);
      return callback();
    });
  };
  ensureChromeDriver = function (version) {
    return function (callback) {
      var bitness, cache$1, platform, tempFilePath, url;
      cache$1 = getArchitecture();
      platform = cache$1.platform;
      bitness = cache$1.bitness;
      url = 'http://chromedriver.storage.googleapis.com/' + version + '/chromedriver_' + platform + bitness + '.zip';
      if (exists(CHROMEDRIVER_PATH))
        return callback();
      console.log('[testium] grabbing selenium chromedriver ' + version);
      tempFilePath = '' + TEMP_PATH + '/chromedriver_' + version;
      if (exists(tempFilePath)) {
        return copy(tempFilePath, CHROMEDRIVER_PATH, callback);
      } else {
        return downloadFile(url, tempFilePath, function () {
          return unzip(tempFilePath, function () {
            return move('' + TEMP_PATH + '/chromedriver', tempFilePath, function () {
              return copy(tempFilePath, CHROMEDRIVER_PATH, function () {
                return fs.chmod(CHROMEDRIVER_PATH, '755', callback);
              });
            });
          });
        });
      }
    };
  };
  makePaths = function () {
    mkdirp.sync(BIN_PATH);
    return mkdirp.sync(TEMP_PATH);
  };
  exit = function (error) {
    if (null != error)
      console.error(error);
    return process.exit(null != error ? 1 : 0);
  };
  makePaths();
  getLatestVersions(SELENIUM_VERSION, CHROMEDRIVER_PATH, function (error, versions) {
    if (null != error)
      return exit(error);
    return async.parallel([
      ensureSelenium(versions.selenium),
      ensureChromeDriver(versions.chromedriver)
    ], exit);
  });
}.call(this);
