// Generated by CoffeeScript 2.0.0-beta7
module.exports = function (error) {
  var attributes, message;
  attributes = JSON.stringify(error);
  message = error.stack;
  if (attributes !== '{}')
    message = '' + message + '  with metadata: ' + attributes + '\n';
  return console.error(message);
};
