// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var assert, cache$, cachedLogs, filterLogs, parseLogs, TYPES;
  assert = require('assertive');
  cache$ = require('./console');
  parseLogs = cache$.parseLogs;
  filterLogs = cache$.filterLogs;
  TYPES = [
    'error',
    'warn',
    'log',
    'debug'
  ];
  cachedLogs = [];
  module.exports = function (driver) {
    return {
      getConsoleLogs: function (type) {
        var cache$1, logs, matched, newLogs, rest;
        if (null != type)
          assert.include(type, TYPES);
        newLogs = parseLogs(driver.getConsoleLogs());
        logs = cachedLogs.concat(newLogs);
        cache$1 = filterLogs(logs, type);
        matched = cache$1.matched;
        rest = cache$1.rest;
        cachedLogs = rest || [];
        return matched || [];
      }
    };
  };
}.call(this);
