// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var commandPort, fromPort, getPortParam, proxy, toPort, truthy, webdriverWorkaround;
  proxy = require('./proxy');
  webdriverWorkaround = require('./webdriver_workaround');
  truthy = require('assertive').truthy;
  getPortParam = function () {
    var port;
    truthy('proxy requires process.argv[2] to be a port number', process.argv[2]);
    port = parseInt(process.argv[2], 10);
    truthy('proxy requires process.argv[2] to be a port number', port);
    return port;
  };
  toPort = getPortParam();
  fromPort = 4445;
  commandPort = 4446;
  proxy(fromPort, toPort, commandPort, webdriverWorkaround);
}.call(this);
