// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var buildCookie, encode;
  encode = function (string) {
    return new Buffer(string).toString('base64');
  };
  buildCookie = function (headers, statusCode) {
    var encodedData;
    encodedData = {
      headers: headers,
      statusCode: statusCode
    };
    encodedData = JSON.stringify(encodedData);
    encodedData = encode(encodedData);
    return '_testium_=' + encodedData + '; path=/';
  };
  module.exports = function (response) {
    var type;
    if (null != response.headers)
      response.headers;
    else
      response.headers = {};
    type = response.headers['content-type'];
    if (response.headers['Set-Cookie'])
      console.log('Existing Set-Cookie Header!! ' + response.headers['Set-Cookie']);
    response.headers['Cache-Control'] = 'no-store';
    response.headers['Set-Cookie'] = buildCookie(response.headers, response.statusCode);
    if (response.statusCode >= 400) {
      console.log('<-- forcing status code from ' + response.statusCode + ' to 200');
      response.statusCode = 200;
    }
    return console.log('<-- Set-Cookie: ' + response.headers['Set-Cookie']);
  };
}.call(this);
