// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cleanup, ensureBinaries, proxyProcess, seleniumProcess, startProcesses;
  cleanup = require('./cleanup');
  startProcesses = require('./process');
  ensureBinaries = require('selenium-download').ensure;
  seleniumProcess = null;
  proxyProcess = null;
  module.exports = {
    ensure: ensureBinaries,
    cleanup: function (callback) {
      return cleanup(seleniumProcess, proxyProcess, callback);
    },
    start: function (seleniumServerUrl, javaHeapSize, logDirectory, applicationPort, callback) {
      return startProcesses(seleniumServerUrl, javaHeapSize, logDirectory, applicationPort, function (error, processes) {
        seleniumProcess = processes.selenium;
        proxyProcess = processes.proxy;
        if (null != error)
          return callback(error);
        if (null != seleniumServerUrl)
          seleniumServerUrl;
        else
          seleniumServerUrl = 'http://127.0.0.1:4444/wd/hub';
        return callback(null, seleniumServerUrl);
      });
    }
  };
}.call(this);
