/*
Copyright (c) 2013, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var AdmZip, async, BIN_PATH, CHROMEDRIVER_PATH, CHROMEDRIVER_VERSION, CHROMEDRIVER_ZIP_PATH, downloadChromeDriver, ensureChromeDriver, ensureSelenium, fs, getArchitecture, http, makePath, mkdirp, SELENIUM_JAR_PATH, SELENIUM_VERSION, unzipChromedriver;
  fs = require('fs');
  http = require('http');
  mkdirp = require('mkdirp');
  async = require('async');
  AdmZip = require('adm-zip');
  BIN_PATH = '' + __dirname + '/../bin';
  CHROMEDRIVER_PATH = '' + BIN_PATH + '/chromedriver';
  CHROMEDRIVER_ZIP_PATH = '' + CHROMEDRIVER_PATH + '.zip';
  CHROMEDRIVER_VERSION = '2.8';
  SELENIUM_JAR_PATH = '' + BIN_PATH + '/selenium.jar';
  SELENIUM_VERSION = '2.39.0';
  ensureSelenium = function (callback) {
    var file, url;
    console.log('[Selenium] checking if standalone server jar exists: ' + SELENIUM_JAR_PATH);
    if (fs.existsSync(SELENIUM_JAR_PATH))
      return console.log('[Selenium] found');
    console.log('[Selenium] standalone server jar');
    url = 'http://selenium.googlecode.com/files/selenium-server-standalone-' + SELENIUM_VERSION + '.jar';
    file = fs.createWriteStream(SELENIUM_JAR_PATH);
    return http.get(url, function (response) {
      response.pipe(file);
      return response.on('end', function () {
        console.log('[Selenium] download complete');
        return callback();
      });
    });
  };
  getArchitecture = function () {
    var bitness, platform;
    platform = process.platform;
    if (!(platform === 'linux' || platform === 'darwin' || platform === 'win32'))
      throw new Error('Unsupported platform #{platform}. Only linux, darwin, and win32 are supported.');
    bitness = process.arch.substr(1);
    if (platform === 'darwin') {
      platform = 'mac';
      bitness = '32';
    }
    if (platform === 'win32') {
      platform = 'win';
      bitness = '32';
    }
    return {
      platform: platform,
      bitness: bitness
    };
  };
  unzipChromedriver = function () {
    var zip;
    zip = new AdmZip(CHROMEDRIVER_ZIP_PATH);
    zip.extractAllTo(BIN_PATH);
    return fs.unlinkSync(CHROMEDRIVER_ZIP_PATH);
  };
  downloadChromeDriver = function (callback) {
    var bitness, cache$, file, platform, url;
    console.log('[ChromeDriver] downloading driver');
    cache$ = getArchitecture();
    platform = cache$.platform;
    bitness = cache$.bitness;
    url = 'http://chromedriver.storage.googleapis.com/' + CHROMEDRIVER_VERSION + '/chromedriver_' + platform + bitness + '.zip';
    file = fs.createWriteStream(CHROMEDRIVER_ZIP_PATH);
    return http.get(url, function (response) {
      response.on('end', function () {
        unzipChromedriver();
        console.log('[ChromeDriver] download complete');
        return callback();
      });
      return response.pipe(file);
    });
  };
  ensureChromeDriver = function (callback) {
    console.log('[ChromeDriver] checking if driver exists: ' + CHROMEDRIVER_PATH);
    if (fs.existsSync(CHROMEDRIVER_PATH))
      return console.log('[ChromeDriver] found');
    return downloadChromeDriver(function () {
      fs.chmodSync(CHROMEDRIVER_PATH, '755');
      return callback();
    });
  };
  makePath = function (callback) {
    return mkdirp(BIN_PATH, callback);
  };
  async.parallel([
    makePath,
    ensureSelenium,
    ensureChromeDriver
  ], function (error) {
    if (null != error)
      console.error(error);
    return process.exit(null != error ? 1 : 0);
  });
}.call(this);
