/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, FALLBACK_CHROMEDRIVER_VERSION, FALLBACK_SELENIUM_VERSION, find, getLatestChromedriverVersion, getLatestSeleniumVersion, parseChrome, parseSelenium, parseSeleniumMinor, parseXml, request;
  FALLBACK_CHROMEDRIVER_VERSION = '2.9';
  FALLBACK_SELENIUM_VERSION = '2.39.0';
  async = require('async');
  request = require('request');
  parseXml = require('xml2js').parseString;
  find = require('underscore').find;
  parseSeleniumMinor = function (result) {
    var prefix, prefixes, versionPath;
    prefixes = result.ListBucketResult.CommonPrefixes;
    prefix = prefixes[prefixes.length - 2];
    versionPath = prefix.Prefix[0];
    return versionPath.substring(0, versionPath.length - 1);
  };
  parseSelenium = function (result) {
    var content, contents;
    contents = result.ListBucketResult.Contents;
    content = find(contents, function (content) {
      return content.Key[0].match(/selenium-server-standalone-/);
    });
    return content.Key[0].match(/(\d+\.\d+\.\d+)/)[0];
  };
  getLatestSeleniumVersion = function (callback) {
    var url;
    url = 'http://selenium-release.storage.googleapis.com/?delimiter=/&prefix=';
    return request(url, function (error, response, body) {
      if (null != error)
        return callback(error);
      return parseXml(body, function (error, result) {
        var minorVersion, parseError;
        if (null != error)
          return callback(error);
        try {
          minorVersion = parseSeleniumMinor(result);
          return request('http://selenium-release.storage.googleapis.com/?delimiter=/&prefix=' + minorVersion + '/', function (error, response, body) {
            if (null != error)
              return callback(error);
            return parseXml(body, function (error, result) {
              var version;
              if (null != error)
                return callback(error);
              version = parseSelenium(result);
              return callback(null, version);
            });
          });
        } catch (e$) {
          parseError = e$;
          return callback(parseError);
        }
      });
    });
  };
  parseChrome = function (result) {
    var prefix, prefixes, versionPath;
    prefixes = result.ListBucketResult.CommonPrefixes;
    prefix = prefixes[prefixes.length - 2];
    versionPath = prefix.Prefix[0];
    return versionPath.substring(0, versionPath.length - 1);
  };
  getLatestChromedriverVersion = function (callback) {
    return request('http://chromedriver.storage.googleapis.com/?delimiter=/&prefix=', function (error, response, body) {
      if (null != error)
        return callback(error);
      return parseXml(body, function (error, result) {
        var parseError, version;
        if (null != error)
          return callback(error);
        version = null;
        error = null;
        try {
          version = parseChrome(result);
        } catch (e$) {
          parseError = e$;
          error = parseError;
        }
        return callback(error, version);
      });
    });
  };
  module.exports = function (callback) {
    return async.parallel([
      getLatestSeleniumVersion,
      getLatestChromedriverVersion
    ], function (error, results) {
      var chromedriver, selenium;
      selenium = null;
      chromedriver = null;
      if (!(null != results ? results[0] : void 0)) {
        selenium = FALLBACK_SELENIUM_VERSION;
        console.log('[testium] Unable to determine latest version of selenium standalone server; using ' + selenium);
        if (null != error)
          console.error(error.stack);
      } else {
        selenium = results[0];
      }
      if (!(null != results ? results.length : void 0) > 1 || !(null != results ? results[1] : void 0)) {
        chromedriver = FALLBACK_CHROMEDRIVER_VERSION;
        console.log('[testium] Unable to determine latest version of selenium chromedriver; using ' + chromedriver);
        if (null != error)
          console.error(error.stack);
      } else {
        chromedriver = results[1];
      }
      return callback(null, {
        selenium: selenium,
        chromedriver: chromedriver
      });
    });
  };
}.call(this);
