// Generated by CoffeeScript 1.9.3

/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var CookieMixin, Hub, assert, createBrowser, decode, each, find, getTestiumCookie, parseTestiumCookie, ref, tryParse, wd;

wd = require('wd');

ref = require('lodash'), find = ref.find, each = ref.each;

assert = require('assertive');

Hub = require('gofer/hub');

tryParse = require('../browser/json').tryParse;

decode = function(value) {
  return (new Buffer(value, 'base64')).toString('utf8');
};

parseTestiumCookie = function(cookie) {
  var value;
  value = decode(cookie.value);
  return tryParse(value);
};

getTestiumCookie = function(cookies) {
  var testiumCookie;
  testiumCookie = find(cookies, {
    name: '_testium_'
  });
  if (testiumCookie == null) {
    throw new Error('Unable to communicate with internal proxy. Make sure you are using relative paths.');
  }
  return parseTestiumCookie(testiumCookie);
};

CookieMixin = {
  _getTestiumCookieField: function(name) {
    return this.allCookies().then(getTestiumCookie).then(function(testiumCookie) {
      return testiumCookie != null ? testiumCookie[name] : void 0;
    });
  },
  getStatusCode: function() {
    return this._getTestiumCookieField('statusCode');
  },
  assertStatusCode: function(status) {
    return this.getStatusCode().then(function(actual) {
      return assert.equal(status, actual);
    });
  }
};

module.exports = createBrowser = function(options, cb) {
  var browser, commandUrl, desiredCapabilities, driverType, driverUrl, hub, ref1, ref2, ref3, targetUrl;
  ref2 = (ref1 = options.proxy) != null ? ref1 : {}, targetUrl = ref2.targetUrl, commandUrl = ref2.commandUrl;
  hub = new Hub();
  wd.addPromiseChainMethod('_sendTestiumCommand', function(pathname, json) {
    return hub.fetch({
      method: 'POST',
      uri: "" + commandUrl + pathname,
      json: json
    }).then();
  });
  each(CookieMixin, function(method, name) {
    return wd.addPromiseChainMethod(name, method);
  });
  wd.addPromiseChainMethod('assertElementHasText', function(selector, text) {
    throw new Error('Not implemented (assertElementHasText)');
  });
  wd.addPromiseChainMethod('navigateTo', function(url, options) {
    if (options == null) {
      options = {};
    }
    return this._sendTestiumCommand('/new-page', {
      url: url
    }).get(url);
  });
  driverType = options.driverType, desiredCapabilities = options.desiredCapabilities, (ref3 = options.selenium, driverUrl = ref3.driverUrl);
  browser = wd.remote(driverUrl, driverType);
  browser.configureHttp({
    baseUrl: targetUrl
  });
  return browser.init(desiredCapabilities).navigateTo('/testium-priming-load').then(function() {
    return browser;
  }).nodeify(cb);
};
