// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var createWriteStream, moment;
  moment = require('moment');
  createWriteStream = require('fs').createWriteStream;
  module.exports = function (logPath) {
    var _write, stream;
    stream = createWriteStream(logPath);
    stream.path = logPath;
    _write = stream.write.bind(stream);
    stream.write = function (message, encoding, callback) {
      return _write(message, encoding, callback);
    };
    stream.log = function (message) {
      var timestamp;
      timestamp = moment().format('HH:mm:ss.SSS');
      return this.write('[SERVICE] ' + timestamp + ' - ' + message + '\n');
    };
    stream.on('error', function (error) {
      return console.error('Error writing to stream ' + logPath + ': ', error.stack);
    });
    return stream;
  };
}.call(this);
