// Generated by CoffeeScript 2.0.0-beta7
lockPref('browser.cache.disk.enable', false);
lockPref('browser.cache.memory.enable', false);
lockPref('browser.cache.offline.enable', false);
lockPref('network.http.use-cache', false);
