// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var async, createLog, DEFAULT_LOG_DIRECTORY, mkdirp, startProxy, startSelenium;
  DEFAULT_LOG_DIRECTORY = '' + __dirname + '/../../../log';
  mkdirp = require('mkdirp');
  async = require('async');
  startSelenium = require('./selenium');
  startProxy = require('./proxy');
  createLog = require('./create_log');
  module.exports = function (seleniumServerUrl, javaHeapSize, logDirectory, applicationPort, callback) {
    var proxyLog, seleniumLog, tasks;
    if (null != logDirectory)
      logDirectory;
    else
      logDirectory = DEFAULT_LOG_DIRECTORY;
    mkdirp.sync(logDirectory);
    seleniumLog = createLog('' + logDirectory + '/selenium.log');
    proxyLog = createLog('' + logDirectory + '/proxy.log');
    tasks = { proxy: startProxy(applicationPort, proxyLog) };
    if (!seleniumServerUrl)
      tasks.selenium = startSelenium(seleniumLog, javaHeapSize);
    return async.parallel(tasks, function (dummySlot, results) {
      var cache$, error, proxy, selenium;
      cache$ = results;
      proxy = cache$.proxy;
      selenium = cache$.selenium;
      error = selenium.error || proxy.error;
      proxy = proxy.process;
      selenium = selenium.process;
      return callback(error, {
        proxy: proxy,
        selenium: selenium
      });
    });
  };
}.call(this);
