// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var isAvailable, logError, portscanner, procError, waitFor;
  portscanner = require('portscanner');
  logError = require('../../log/error');
  isAvailable = function (port, callback) {
    return portscanner.checkPortStatus(port, '127.0.0.1', function (error, status) {
      if (null != error)
        return callback(error);
      return callback(null, status === 'closed');
    });
  };
  procError = function (proc) {
    var message;
    message = 'Process "' + proc.name + '" crashed. See log at: ' + proc.logPath + '.';
    if ((null != proc.error ? proc.error.length : void 0) > 0)
      message += '\n' + proc.error.trim();
    return new Error(message);
  };
  waitFor = function (proc, port, timeout, callback) {
    var check, error, startTime;
    if (!proc.alive) {
      error = procError(proc);
      return callback(error);
    }
    startTime = Date.now();
    check = function () {
      return portscanner.checkPortStatus(port, '127.0.0.1', function (error, status) {
        var timedOut;
        if (null != error)
          logError(error.message);
        if (!proc.alive) {
          error = procError(proc);
          return callback(error);
        }
        if (null != error || status === 'closed') {
          if (Date.now() - startTime >= timeout) {
            timedOut = true;
            return callback(null, timedOut);
          }
          return setTimeout(check, 100);
        } else {
          return callback();
        }
      });
    };
    return check();
  };
  module.exports = {
    isAvailable: isAvailable,
    waitFor: waitFor
  };
}.call(this);
