// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var spawn;
  spawn = require('child_process').spawn;
  module.exports = function (command, args, name, logStream) {
    var error, proc;
    proc = spawn(command, args);
    proc.alive = true;
    proc.name = name;
    proc.logPath = logStream.path;
    proc.stdout.pipe(logStream);
    proc.stderr.pipe(logStream);
    error = '';
    proc.stderr.on('data', function (data) {
      return error += data.toString();
    });
    proc.on('exit', function (exitCode) {
      if (exitCode !== 0)
        proc.error = error;
      return proc.alive = false;
    });
    return proc;
  };
}.call(this);
