// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var partialPipe, spawn;
  spawn = require('child_process').spawn;
  partialPipe = function (source, dest) {
    return source.on('data', dest.write);
  };
  module.exports = function (command, args, name, logStream) {
    var proc;
    proc = spawn(command, args);
    proc.alive = true;
    proc.name = name;
    proc.logPath = logStream.path;
    partialPipe(proc.stdout, logStream);
    partialPipe(proc.stderr, logStream);
    proc.error = '';
    proc.stderr.on('data', function (data) {
      return proc.error += data.toString();
    });
    proc.on('exit', function (exitCode) {
      return proc.alive = false;
    });
    return proc;
  };
}.call(this);
