// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var browserInstance, Driver, PROXY_COMMAND_PORT, store, TARGET_PORT;
  Driver = require('../api');
  store = require('./store');
  TARGET_PORT = 4445;
  PROXY_COMMAND_PORT = 4446;
  browserInstance = null;
  module.exports.getBrowser = function () {
    var browser, browserOptions, cache$, http, logDirectory, options, seleniumServer;
    if (null != browserInstance)
      return browserInstance;
    cache$ = store.get();
    seleniumServer = cache$.seleniumServer;
    logDirectory = cache$.logDirectory;
    browser = cache$.browser;
    http = cache$.http;
    browserOptions = {
      browserName: browser,
      applicationCacheEnabled: false
    };
    options = {
      logDirectory: logDirectory,
      http: http
    };
    browserInstance = new Driver(TARGET_PORT, PROXY_COMMAND_PORT, seleniumServer, browserOptions, options);
    browserInstance.setPageSize({
      height: 768,
      width: 1024
    });
    return browserInstance;
  };
}.call(this);
