// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var browser, exit, getBrowser, logError;
  logError = require('../log/error');
  getBrowser = require('./browser').getBrowser;
  browser = getBrowser();
  global.exitMocha = function (done) {
    if (null != browser) {
      browser.close(done);
      return browser = void 0;
    } else {
      return done();
    }
  };
  exit = function (error) {
    logError(error);
    try {
      console.error('Attempting to close the WebDriver session');
      global.exitMocha(function () {
        return process.exit(-2);
      });
    } catch (e$) {
      error = e$;
      logError(error);
      process.exit(-3);
    }
    return setTimeout(function () {
      return process.exit(-4);
    }, 1e3);
  };
  process.on('uncaughtException', exit);
  before(function () {
    return browser.navigateTo('/testium-priming-load');
  });
  after(global.exitMocha);
}.call(this);
