// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var values;
  values = {};
  module.exports = {
    set: function (options) {
      values.logDirectory = options.logDirectory;
      values.screenshotDirectory = options.screenshotDirectory;
      values.browser = options.browser;
      values.http = options.http || {};
      return values.seleniumServer = options.seleniumServer;
    },
    get: function () {
      return values;
    }
  };
}.call(this);
