// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, existsSync, getFile, path, uniqueFile, writeFileSync;
  path = require('path');
  cache$ = require('fs');
  writeFileSync = cache$.writeFileSync;
  existsSync = cache$.existsSync;
  module.exports = function (directory, title, data, encoding) {
    var file;
    if (null == encoding)
      encoding = 'base64';
    file = getFile(directory, title);
    writeFileSync(file, data, encoding);
    return file;
  };
  getFile = function (directory, title) {
    var filePath, name;
    name = title.replace(/[^\w]/g, '_').replace(/_{2,}/g, '_').substr(0, 40);
    filePath = path.join(directory, name);
    return uniqueFile(filePath);
  };
  uniqueFile = function (file) {
    var counter, testPath;
    testPath = file;
    counter = null;
    while (existsSync('' + testPath + '.png')) {
      counter || (counter = 0);
      counter++;
      testPath = '' + file + counter;
    }
    return '' + testPath + '.png';
  };
}.call(this);
